/**
 * 16×16 character-map pixel sprites (R-11.1). Each character is a palette role; '.' is
 * transparent. Object colors are fixed and hue-shifted by hand: shadows lean violet,
 * highlights lean warm yellow.
 */

export const SPRITE_COLORS: Record<string, string> = {
  k: '#1b1a2e', // outline (violet-black)
  d: '#3b3657', // cool shadow
  m: '#7d8aa3', // metal
  l: '#c9d4e0', // metal highlight
  b: '#2f5fa8', // solar cell
  c: '#6ec3e8', // cell highlight
  w: '#f4f1de', // warm white
  y: '#f2c14e', // sun yellow
  o: '#e07a3f', // orange
  r: '#c8423b', // warning red
  g: '#2e6b3f', // deep green (shadow leans blue)
  G: '#58a84b', // green
  L: '#a5d65a', // leaf highlight (leans yellow)
  n: '#5a3d2e', // trunk shadow
  N: '#9a6a3f', // trunk
  p: '#f29bb6', // blossom
  P: '#7a3e8e', // toxic violet
  t: '#9be34a', // toxic glow
  u: '#8a4b2a', // rust
  U: '#b8683a', // rust highlight
  s: '#6c6a78', // smoke
  S: '#a19fb0', // smoke highlight
  a: '#38c7b8', // water turquoise
  e: '#ffe27a', // energy glow
};

export const SPRITES: Record<string, string[]> = {
  sanctuary: [
    '.......kk.......',
    '......kLLk......',
    '.....kLGGLk.....',
    '....kLGGGGLk....',
    '...kGGGGGGGGk...',
    '..kkkkkkkkkkkk..',
    '...kwwwwwwwwk...',
    '...kwyywwyywk...',
    '...kwyywwyywk...',
    '...kwwwkkwwwk...',
    '...kwwwkykwwk...',
    '...kwwwkykwwk...',
    '..kGGGGGGGGGGk..',
    '.kGLGGLGGLGGLGk.',
    '..kkkkkkkkkkkk..',
    '................',
  ],
  solar: [
    '................',
    '................',
    '.kkkkkkkkkkkkkk.',
    '.kccbbbbcbbbbbk.',
    '.kcbbbbcbbbbbbk.',
    '.kkkkkkkkkkkkkk.',
    '.kbbbbcbbbbbcbk.',
    '.kbbbcbbbbbcbbk.',
    '.kkkkkkkkkkkkkk.',
    '.kdddddddddddddk',
    '......kmmk......',
    '......kmlk......',
    '......kmlk......',
    '....kkmmmmkk....',
    '...kdddddddk....',
    '................',
  ],
  wind: [
    '.......kk.......',
    '......kwwk......',
    '......kwlk......',
    '..kk..kwlk......',
    '.kwwk.kwlk......',
    '..kwwkkwwk..kk..',
    '....kwkykkwwwwk.',
    '......kkwk.kkk..',
    '......kwlkk.....',
    '......kwlk.kk...',
    '......kwlk..kwk.',
    '......kwlk...kk.',
    '......kmlk......',
    '......kmlk......',
    '.....kmmmmk.....',
    '....kdddddddk...',
  ],
  scrubber: [
    '................',
    '.....kkkkkk.....',
    '....kmllllmk....',
    '...kmlaaaalmk...',
    '...kmaaccaamk...',
    '...kmaaccaamk...',
    '...kmlaaaalmk...',
    '....kmmmmmmk....',
    '...kkkkkkkkkk...',
    '..kmmlmmmmlmmk..',
    '..kmGGGGGGGGmk..',
    '..kmGLGLGLGGmk..',
    '..kmmmmmmmmmmk..',
    '..kdddddddddddk.',
    '..kk..kk..kk.k..',
    '................',
  ],
  purifier: [
    '................',
    '......kkkk......',
    '.....kallak.....',
    '....kaacclak....',
    '...kaaaccaaak...',
    '...kaaaaaaaak...',
    '....kaaaaaak....',
    '.....kkkkkk.....',
    '..kkkkmmmmkkkk..',
    '.kmllmmmmmmllmk.',
    '.kmmmmwwwwmmmmk.',
    '.kmmmmwaawmmmmk.',
    '.kmmmmwwwwmmmmk.',
    '.kddddddddddddk.',
    '..kkkkkkkkkkkk..',
    '................',
  ],
  recycler: [
    '................',
    '...kkkkkkkkkk...',
    '..kmllllllllmk..',
    '..kmGGmmmmGGmk..',
    '..kmGmmkkmmGmk..',
    '..kmmmkyykmmmk..',
    '..kmmkyyyykmmk..',
    '..kmmkyyyykmmk..',
    '..kmmmkyykmmmk..',
    '..kmGmmkkmmGmk..',
    '..kmGGmmmmGGmk..',
    '..kmllllllllmk..',
    '..kddddddddddk..',
    '...kkkkkkkkkk...',
    '................',
    '................',
  ],
  battery: [
    '................',
    '......kkkk......',
    '.....kmllmk.....',
    '...kkkkkkkkkk...',
    '...kmmmmmmmmk...',
    '...kmGGGGGGmk...',
    '...kmGLeLGGmk...',
    '...kmGGeeGGmk...',
    '...kmGeeLGGmk...',
    '...kmGGeGGGmk...',
    '...kmGGGGGGmk...',
    '...kmGGGGGGmk...',
    '...kmmmmmmmmk...',
    '...kddddddddk...',
    '....kkkkkkkk....',
    '................',
  ],
  sealer: [
    '................',
    '....kkkkkkkk....',
    '...kmllllllmk...',
    '...kmmmmmmmmk...',
    '....kGGGGGGk....',
    '....kGLGGLGk....',
    '....kmmmmmmk....',
    '....kmuuuumk....',
    '....kmuUuumk....',
    '....kmuuuumk....',
    '....kmuuUumk....',
    '....kmuuuumk....',
    '...kmmmmmmmmk...',
    '..kddddddddddk..',
    '..kkkkkkkkkkkk..',
    '................',
  ],
  stack: [
    '..sS..Ss........',
    '.sSSs.SSs.......',
    '..sSSsSs........',
    '....sSs.........',
    '.....kkkkk......',
    '.....kuUuk......',
    '.....kuuuk......',
    '.....krrrk......',
    '.....kuuUk......',
    '.....kuuuk......',
    '.....krrrk......',
    '....kuuuuuk.....',
    '....kuUuuuk.....',
    '...kuuuuuuuk....',
    '..kdddddddddk...',
    '................',
  ],
  ruin: [
    '................',
    '................',
    '...kk...........',
    '..kuUk....kk....',
    '..kuuk...kmlk...',
    '..kuuk..kmmmk...',
    '..kuukkkkmmk....',
    '..kuuuuUuukk....',
    '.kuukkPPkkuk....',
    '.kuktttPPtkuk...',
    'kuukPtPtPPkuuk..',
    'kddkkPPtPkkddk..',
    '.kddddkkkddddk..',
    '..kkkkkkkkkkk...',
    '................',
    '................',
  ],
  grass0: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '.......k........',
    '......kLk.......',
    '......kGk.k.....',
    '..k....kkkLk....',
    '.kLk...kGGk.....',
    '..kGk..kGk......',
    '................',
  ],
  grass: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '...k......k.....',
    '..kLk....kLk.k..',
    '..kGk.k..kGkkLk.',
    '.kGGkkLk.kGGkGk.',
    '.kGgkkGkkGgkGGk.',
    'kLGgkGGkkGgkGgk.',
    'kGgGkGgkLGgGGgk.',
    'kggGgGggGgggGgk.',
    '.kkkkkkkkkkkkk..',
    '................',
  ],
  shrub0: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '......kk........',
    '.....kLGk.......',
    '....kLGGGk......',
    '.....kGgk.......',
    '......kn........',
    '......kN........',
    '.....kkkk.......',
    '................',
  ],
  shrub: [
    '................',
    '................',
    '................',
    '................',
    '.....kkkkk......',
    '...kkLGGGLkk....',
    '..kLGGpGGGGLk...',
    '.kLGGGGGGpGGGk..',
    '.kGGpGGGGGGGgk..',
    '.kGGGGGgGGpGgk..',
    '..kgGGpGggGggk..',
    '...kggggggggk...',
    '....kkknNkkk....',
    '......knNk......',
    '.....kkkkkk.....',
    '................',
  ],
  tree0: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '.......kk.......',
    '......kLLk......',
    '.....kLGGLk.....',
    '......kGGk......',
    '.......kk.......',
    '.......kN.......',
    '.......kN.......',
    '.......kN.......',
    '......kkkk......',
    '................',
    '................',
  ],
  tree: [
    '......kkkk......',
    '....kkLLLLkk....',
    '...kLLGGGGGLk...',
    '..kLGGGpGGGGGk..',
    '.kLGGGGGGGGpGGk.',
    '.kGGpGGGGGGGGgk.',
    '.kGGGGGGGpGGGgk.',
    '.kgGGGGGGGGGggk.',
    '..kgGgGGGGgGgk..',
    '...kkgggggggk...',
    '.....kknNkk.....',
    '.......nNk......',
    '.......nNk......',
    '......knNNk.....',
    '.....kkkkkkk....',
    '................',
  ],
  coin: [
    '................',
    '................',
    '.....kkkkkk.....',
    '....kyyyyyyk....',
    '...kywwyyyyok...',
    '..kywyyooyyyok..',
    '..kyyyoyyyyyok..',
    '..kyyyoyyyyyok..',
    '..kyyyyooyyyok..',
    '..kyyyyyyoyyok..',
    '..kyyyooyyyyok..',
    '...kyyyyyyyok...',
    '....kooooook....',
    '.....kkkkkk.....',
    '................',
    '................',
  ],
  bolt: [
    '................',
    '........kkkk....',
    '.......keeek....',
    '......keeek.....',
    '.....keeek......',
    '....keeekkkkk...',
    '...keeeeeeeek...',
    '...kkkkkeeek....',
    '.......keeek....',
    '......keeek.....',
    '.....keeek......',
    '.....keek.......',
    '....keek........',
    '....kek.........',
    '....kk..........',
    '................',
  ],
  hand: [
    '................',
    '.....k.k.k......',
    '....kwkwkwk.....',
    '....kwkwkwkk....',
    '....kwkwkwkwk...',
    '....kwwwwwkwk...',
    '.kk.kwwwwwwwk...',
    'kwwkkwwwwwwwk...',
    '.kwwkwwwwwwwk...',
    '..kwwwwwwwwk....',
    '...kwwwwwwwk....',
    '....kwwwwwk.....',
    '.....kkkkk......',
    '..a.....a...a...',
    '...a..a...a.....',
    '................',
  ],
  up: [
    '................',
    '.......kk.......',
    '......kGGk......',
    '.....kGLLGk.....',
    '....kGLGGLGk....',
    '...kGLGGGGLGk...',
    '..kkkkGGGGkkkk..',
    '.....kGGGGk.....',
    '.....kGGGGk.....',
    '.....kGGGGk.....',
    '.....kgGGgk.....',
    '.....kkkkkk.....',
    '................',
    '...kkkkkkkkkk...',
    '...kyyyyyyyyk...',
    '...kkkkkkkkkk...',
  ],
  toggle: [
    '................',
    '................',
    '.......kk.......',
    '.......kk.......',
    '....kk.kk.kk....',
    '...kl..kk..lk...',
    '..kl...kk...lk..',
    '..kl........lk..',
    '..kl........lk..',
    '..kl........lk..',
    '...kl......lk...',
    '....kll..llk....',
    '.....kkllkk.....',
    '................',
    '................',
    '................',
  ],
  remove: [
    '................',
    '................',
    '..kk........kk..',
    '.krrk......krrk.',
    '.krrrk....krrrk.',
    '..krrrk..krrrk..',
    '...krrrkkrrrk...',
    '....krrrrrrk....',
    '....krrrrrrk....',
    '...krrrkkrrrk...',
    '..krrrk..krrrk..',
    '.krrrk....krrrk.',
    '.krrk......krrk.',
    '..kk........kk..',
    '................',
    '................',
  ],
  salvage: [
    '................',
    '................',
    '.......kk.......',
    '......kGGk......',
    '.....kGLkGk.....',
    '....kGLk.kGk....',
    '...kGGk...kGk...',
    '..kkkkk...kkkkk.',
    '...kGk.....kGk..',
    '....kGk...kGk...',
    '.kk..kGk.kGk..k.',
    '.kGk..kGGGk..kGk',
    '..kGGGGGGGGGGGk.',
    '...kkkkkkkkkkk..',
    '................',
    '................',
  ],
  leaf: ['..kk', '.kLk', 'kGGk', 'kk..'],
  zz: ['kkk.....', '..k.....', '.k..kkk.', 'kkk...k.', '.....k..', '....kkk.'],
  pause: ['kk.kk', 'kk.kk', 'kk.kk', 'kk.kk'],
};

const cache = new Map<string, HTMLCanvasElement>();

/** Rasterises a sprite once into an offscreen canvas at 1 px per character. */
export function spriteCanvas(name: string, colors: Record<string, string> = SPRITE_COLORS): HTMLCanvasElement {
  const key = colors === SPRITE_COLORS ? name : `${name}|${JSON.stringify(colors)}`;
  const hit = cache.get(key);
  if (hit) return hit;
  const rows = SPRITES[name];
  if (!rows) throw new Error(`unknown sprite ${name}`);
  const c = document.createElement('canvas');
  c.width = rows[0]!.length;
  c.height = rows.length;
  const ctx = c.getContext('2d')!;
  rows.forEach((row, y) => {
    for (let x = 0; x < row.length; x++) {
      const ch = row[x]!;
      if (ch === '.') continue;
      ctx.fillStyle = colors[ch] ?? '#ff00ff';
      ctx.fillRect(x, y, 1, 1);
    }
  });
  cache.set(key, c);
  return c;
}

/** A crisp data-URL icon for DOM buttons. */
export function spriteDataUrl(name: string, scale = 2): string {
  const src = spriteCanvas(name);
  const c = document.createElement('canvas');
  c.width = src.width * scale;
  c.height = src.height * scale;
  const ctx = c.getContext('2d')!;
  ctx.imageSmoothingEnabled = false;
  ctx.drawImage(src, 0, 0, c.width, c.height);
  return c.toDataURL();
}
